'use client';

import { useState } from 'react';
import { X, Copy, Check, Download, Share2 } from 'lucide-react';
import type { Script } from '@/data/scripts';

interface Props {
  scripts: Script[];
  onClose: () => void;
}

export default function SharePipeline({ scripts, onClose }: Props) {
  const [copied, setCopied] = useState(false);

  const greenlit = scripts.filter((s) => s.rating === 'greenlight');
  const considering = scripts.filter((s) => s.rating === 'consider');

  const generateText = () => {
    let text = '🟢 GreenLight — Script Pipeline\n';
    text += `Generated: ${new Date().toLocaleDateString('en-US', { month: 'long', day: 'numeric', year: 'numeric' })}\n\n`;

    if (greenlit.length > 0) {
      text += `━━━ GREENLIT (${greenlit.length}) ━━━\n\n`;
      greenlit.forEach((s, i) => {
        text += `${i + 1}. ${s.title}\n`;
        text += `   Author: ${s.author}\n`;
        text += `   Genre: ${s.genre} | Format: ${s.format} | ${s.pages} pages\n`;
        text += `   Logline: ${s.logline}\n`;
        text += `   Comps: ${s.comparables}\n`;
        text += `   Via: ${s.submittedBy}\n`;
        if (s.notes) text += `   Notes: ${s.notes}\n`;
        text += '\n';
      });
    }

    if (considering.length > 0) {
      text += `━━━ CONSIDERING (${considering.length}) ━━━\n\n`;
      considering.forEach((s, i) => {
        text += `${i + 1}. ${s.title}\n`;
        text += `   Author: ${s.author}\n`;
        text += `   Genre: ${s.genre} | Format: ${s.format} | ${s.pages} pages\n`;
        text += `   Logline: ${s.logline}\n`;
        text += `   Comps: ${s.comparables}\n`;
        text += '\n';
      });
    }

    text += '━━━━━━━━━━━━━━━━━━━━━━━━━━━\n';
    text += 'Generated by GreenLight 🟢\n';
    return text;
  };

  const handleCopy = async () => {
    try {
      await navigator.clipboard.writeText(generateText());
      setCopied(true);
      setTimeout(() => setCopied(false), 2000);
    } catch {
      // Fallback
      const ta = document.createElement('textarea');
      ta.value = generateText();
      document.body.appendChild(ta);
      ta.select();
      document.execCommand('copy');
      document.body.removeChild(ta);
      setCopied(true);
      setTimeout(() => setCopied(false), 2000);
    }
  };

  const handleDownload = () => {
    const text = generateText();
    const blob = new Blob([text], { type: 'text/plain' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = `greenlight-pipeline-${new Date().toISOString().split('T')[0]}.txt`;
    document.body.appendChild(a);
    a.click();
    document.body.removeChild(a);
    URL.revokeObjectURL(url);
  };

  const handleNativeShare = async () => {
    if (navigator.share) {
      try {
        await navigator.share({
          title: 'GreenLight Pipeline',
          text: generateText(),
        });
      } catch {
        // User cancelled
      }
    }
  };

  return (
    <div className="fixed inset-0 z-50 flex items-end justify-center sm:items-center">
      <div className="absolute inset-0 bg-black/60 backdrop-blur-sm" onClick={onClose} />
      <div className="relative z-10 max-h-[80vh] w-full max-w-lg overflow-y-auto rounded-t-3xl border border-midnight-600 bg-midnight-800 sm:rounded-3xl">
        <div className="flex items-center justify-between border-b border-midnight-600 p-6">
          <h2 className="text-xl font-bold text-white">Share Pipeline</h2>
          <button type="button" onClick={onClose} className="rounded-full bg-midnight-700 p-2">
            <X className="h-5 w-5 text-midnight-300" />
          </button>
        </div>

        <div className="p-6">
          <p className="mb-4 text-sm text-midnight-300">
            {greenlit.length} greenlit · {considering.length} considering
          </p>

          {/* Preview */}
          <div className="mb-6 max-h-48 overflow-y-auto rounded-xl bg-midnight-900 p-4 font-mono text-xs text-midnight-300">
            <pre className="whitespace-pre-wrap">{generateText()}</pre>
          </div>

          {/* Actions */}
          <div className="space-y-3">
            <button
              type="button"
              onClick={handleCopy}
              className="flex w-full items-center justify-center gap-2 rounded-2xl bg-green-500 py-4 text-lg font-semibold text-white transition hover:bg-green-600"
            >
              {copied ? <Check className="h-5 w-5" /> : <Copy className="h-5 w-5" />}
              {copied ? 'Copied!' : 'Copy to Clipboard'}
            </button>

            <div className="flex gap-3">
              <button
                type="button"
                onClick={handleDownload}
                className="flex flex-1 items-center justify-center gap-2 rounded-2xl bg-midnight-700 py-3 font-medium text-midnight-200 transition hover:bg-midnight-600"
              >
                <Download className="h-4 w-4" />
                Download .txt
              </button>

              {typeof navigator !== 'undefined' && 'share' in navigator && (
                <button
                  type="button"
                  onClick={handleNativeShare}
                  className="flex flex-1 items-center justify-center gap-2 rounded-2xl bg-midnight-700 py-3 font-medium text-midnight-200 transition hover:bg-midnight-600"
                >
                  <Share2 className="h-4 w-4" />
                  Share
                </button>
              )}
            </div>
          </div>
        </div>
      </div>
    </div>
  );
}
